server:
  port: 8008
spring:
  application:
    name: swag-artist

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
#      defaultZone: http://swag-discovery:8703/eureka/
      defaultZone: http://localhost:8703/eureka/
    enabled: false
